baseURL      = "https://dustinkeys.github.io/nathanielkeys.github.io/"
title        = "Nathaniel Keys"
languageCode = "en-us"
theme        = "hugo-ink"
canonifyURLs = true

[pagination]
  pagerSize = 10

relativeURLs = true

[[menu.main]]
  name   = "About"
  url    = "/about/"
  weight = 1

[[menu.main]]
  name   = "Books"
  url    = "/books/"
  weight = 2
