baseURL      = "https://nathanielkeys.github.io/"
title        = "Nathaniel Keys"
languageCode = "en-us"
theme        = "hugo-ink"
pagerSize = 10
canonifyURLs = true

[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 1

  [[menu.main]]
  name = "Books"
  url  = "/books/"
  weight = 2
